name: Database Cleanup

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Call Cleanup API
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST ${{ secrets.APP_URL }} \
            -H "API_KEY: ${{ secrets.CLEANUP_API_KEY }}" \
            -H "Content-Type: application/json")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Cleanup API failed with status code $RESPONSE"
            cat response.json  # Print error message from API
            exit 1  # Fail the GitHub Action
          fi
