name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Test SSH connection (optional)
      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no deploy@37.187.181.189 "echo 'Connection successful!'"

      # Deploy your app (or run commands)
      - name: Deploy
        run: |
          ssh deploy@37.187.181.189 << 'EOF'
            # Put your commands here, for example:
            cd /home/deploy/portfolio3.0
            git pull origin master
            npm install
            pm2 restart portfolio
          EOF
