name: Deploy to Server

on:
  push:
    branches:
      - master  # Deploy when pushing to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 37.187.181.189 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh deploy@37.187.181.189 << 'EOF'
            cd /home/deploy/portfolio3.0
            git pull origin master
            npm install
            npm run build
            pm2 restart portfolio || pm2 start "npm run start" --name portfolio
            pm2 save
          EOF
